dataset:
  base_dir: /mnt/Data/jwandas/Code/dataset_patches
  patch_size: 512
  overlap: 0.5

training:
  max_epochs: 150
  batch_size: 16
  num_workers: 4
  patience: 25

model:
  type: AttentionUnet
  lr: 1e-4
  weight_decay: 2.35e-08
  channels: [32,64,128,256,512]

  