dataset:
  base_dir: /mnt/Data/jwandas/Code/dataset_patches
  patch_size: 512
  overlap: 0.5

training:
  max_epochs: 80
  batch_size: 16
  num_workers: 12
  patience: 15
  n_trials: 100

model:
  type: AttentionUnet
  
tune:
  lr_min: 1e-8
  lr_max: 1e-2
  weight_decay_min: 1e-8
  weight_decay_max: 1e-2